In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

df = pd.read_csv('diabetes_cleaned_numeric.csv')

In [7]:
from sklearn.model_selection import train_test_split

X = df.drop(columns='readmitted')
y = df.readmitted
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFECV
from sklearn.metrics import confusion_matrix


estimator = LogisticRegression(C=1e5,class_weight='balanced',multi_class='ovr',solver='liblinear',random_state=5)
selector = RFECV(estimator, step=1, cv=5,verbose=1)
selector = selector.fit(X_train, y_train)

Fitting estimator with 149 features.
Fitting estimator with 148 features.
Fitting estimator with 147 features.
Fitting estimator with 146 features.
Fitting estimator with 145 features.
Fitting estimator with 144 features.
Fitting estimator with 143 features.
Fitting estimator with 142 features.
Fitting estimator with 141 features.
Fitting estimator with 140 features.
Fitting estimator with 139 features.
Fitting estimator with 138 features.
Fitting estimator with 137 features.
Fitting estimator with 136 features.
Fitting estimator with 135 features.
Fitting estimator with 134 features.
Fitting estimator with 133 features.
Fitting estimator with 132 features.
Fitting estimator with 131 features.
Fitting estimator with 130 features.
Fitting estimator with 129 features.
Fitting estimator with 128 features.
Fitting estimator with 127 features.
Fitting estimator with 126 features.
Fitting estimator with 125 features.
Fitting estimator with 124 features.
Fitting estimator with 123 features.
F

Fitting estimator with 71 features.
Fitting estimator with 70 features.
Fitting estimator with 69 features.
Fitting estimator with 68 features.
Fitting estimator with 67 features.
Fitting estimator with 66 features.
Fitting estimator with 65 features.
Fitting estimator with 64 features.
Fitting estimator with 63 features.
Fitting estimator with 62 features.
Fitting estimator with 61 features.
Fitting estimator with 60 features.
Fitting estimator with 59 features.
Fitting estimator with 58 features.
Fitting estimator with 57 features.
Fitting estimator with 56 features.
Fitting estimator with 55 features.
Fitting estimator with 54 features.
Fitting estimator with 53 features.
Fitting estimator with 52 features.
Fitting estimator with 51 features.
Fitting estimator with 50 features.
Fitting estimator with 49 features.
Fitting estimator with 48 features.
Fitting estimator with 47 features.
Fitting estimator with 46 features.
Fitting estimator with 45 features.
Fitting estimator with 44 fe

Fitting estimator with 140 features.
Fitting estimator with 139 features.
Fitting estimator with 138 features.
Fitting estimator with 137 features.
Fitting estimator with 136 features.
Fitting estimator with 135 features.
Fitting estimator with 134 features.
Fitting estimator with 133 features.
Fitting estimator with 132 features.
Fitting estimator with 131 features.
Fitting estimator with 130 features.
Fitting estimator with 129 features.
Fitting estimator with 128 features.
Fitting estimator with 127 features.
Fitting estimator with 126 features.
Fitting estimator with 125 features.
Fitting estimator with 124 features.
Fitting estimator with 123 features.
Fitting estimator with 122 features.
Fitting estimator with 121 features.
Fitting estimator with 120 features.
Fitting estimator with 119 features.
Fitting estimator with 118 features.
Fitting estimator with 117 features.
Fitting estimator with 116 features.
Fitting estimator with 115 features.
Fitting estimator with 114 features.
F

Fitting estimator with 62 features.
Fitting estimator with 61 features.
Fitting estimator with 60 features.
Fitting estimator with 59 features.
Fitting estimator with 58 features.
Fitting estimator with 57 features.
Fitting estimator with 56 features.
Fitting estimator with 55 features.
Fitting estimator with 54 features.
Fitting estimator with 53 features.
Fitting estimator with 52 features.
Fitting estimator with 51 features.
Fitting estimator with 50 features.
Fitting estimator with 49 features.
Fitting estimator with 48 features.
Fitting estimator with 47 features.
Fitting estimator with 46 features.
Fitting estimator with 45 features.
Fitting estimator with 44 features.
Fitting estimator with 43 features.
Fitting estimator with 42 features.
Fitting estimator with 41 features.
Fitting estimator with 40 features.
Fitting estimator with 39 features.
Fitting estimator with 38 features.
Fitting estimator with 37 features.
Fitting estimator with 36 features.
Fitting estimator with 35 fe

In [24]:
result = pd.Series(selector.ranking_,index=X_train.columns).sort_values()
result

discharge_disposition_id_11      1
admission_type_id_7              1
admission_source_id_25           1
admission_source_id_10           1
admission_source_id_22           2
                              ... 
diag_3_Genitourinary           142
age                            143
num_medications                144
num_lab_procedures             145
admission_source_id_11         146
Length: 149, dtype: int64

In [35]:
best = selector.estimator_
best.get_params()

{'C': 100000.0,
 'class_weight': 'balanced',
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'ovr',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': 5,
 'solver': 'liblinear',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [39]:
best.coef_

array([[ 8.67405059, 10.41804724,  7.22790506,  6.53342184],
       [-5.90404594, -8.11335978, -4.44328219, -3.73307898],
       [-6.77505729, -9.22504141, -5.32436934, -4.62609817]])

In [45]:
predicts = best.predict(X_train[X_train.columns[selector.support_]])
confusion_matrix(y_train,predicts)

array([[34042,     0,     0],
       [17815,     0,     0],
       [ 4980,     0,     0]])

In [28]:
selector.grid_scores_

array([0.59894083, 0.59894083, 0.59894083, 0.59895842, 0.59895842,
       0.59895842, 0.59895842, 0.59895842, 0.59892323, 0.59888804,
       0.59888804, 0.59887045, 0.59887045, 0.59887045, 0.59887045,
       0.59881766, 0.59881766, 0.59878248, 0.59784995, 0.59681195,
       0.59681195, 0.59478855, 0.59471817, 0.59464781, 0.59410242,
       0.59308193, 0.59258933, 0.59107626, 0.59003816, 0.5902317 ,
       0.58989742, 0.58977427, 0.58961592, 0.59044288, 0.59285315,
       0.5963897 , 0.5964073 , 0.59586188, 0.59572112, 0.59568593,
       0.59501733, 0.59461266, 0.5936098 , 0.59318755, 0.59320514,
       0.59315235, 0.59299401, 0.59320514, 0.59339866, 0.59065388,
       0.59309955, 0.59192074, 0.58861313, 0.58713509, 0.58718788,
       0.58618498, 0.58685356, 0.58676559, 0.58553408, 0.58479513,
       0.58331726, 0.58280703, 0.58303574, 0.58300058, 0.58337004,
       0.58358118, 0.58391548, 0.58303575, 0.58356361, 0.58437291,
       0.58277192, 0.58250799, 0.58261354, 0.58268392, 0.58310

In [37]:
X_train.columns[selector.support_]

Index(['admission_type_id_7', 'discharge_disposition_id_11',
       'admission_source_id_10', 'admission_source_id_25'],
      dtype='object')